In [4]:
#NumPy
import numpy as np

In [5]:
 # Creating a Python list "my_list".
my_list = [-1,0,1]
# Well, it's a good idea to confirm items in "my_list" and its type! 
print(my_list, type(my_list))

[-1, 0, 1] <class 'list'>


In [6]:
my_array = np.array(my_list)
print( my_array, type(my_array) )

[-1  0  1] <class 'numpy.ndarray'>


In [7]:
import numpy as np
# Let's create and cast a list of list to generate 2-D array
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_matrix))
print( my_matrix )
# Two-dimensional array from Matrix
matrix_one = np.array(my_matrix)
print(type(matrix_one))
print(matrix_one)

<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# similar to range() in Python, up to but not including 10
print( np.arange(0,10) )

# We can give a step (2 in this case)
print( np.arange(0,11,2) )

# We can give the step and dtype
print( np.arange(0,10,2, dtype=float) )

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
[0. 2. 4. 6. 8.]


In [9]:
# start from 1 & end at 15 with 10 evenly spaced points b/w 1 to 15.
print( np.linspace(1, 15, 10) )

# Let's find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(5, 15, 9, retstep=True)
print( my_linspace )

# We can grab array and step size separately.
print('array is: ',my_linspace[0])
print('stepsize is: ', my_linspace[1])

[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]
(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)
array is:  [ 5.    6.25  7.5   8.75 10.   11.25 12.5  13.75 15.  ]
stepsize is:  1.25


In [10]:
import numpy as np
array_arange = np.arange(16) # using arange()
array_randint = np.random.randint(0,100,10) # using randint()

# Let's take vector array, array_arange
print("Shape : ", array_arange.shape)
# As from its name, size of an array
print("Size : ", array_arange.size)
# type attribute returns the type of the data in the array.
print("Type : ", array_arange.dtype)
 # Notice the two sets of brackets in the output, 
 #we are using reshape() to convert 1-D array to 2-D array/matrix
print("Reshaped : ", array_arange.reshape(4,4))

print("New shape : ", array_arange.reshape(4,4).shape )
print("New shape : ",  array_arange.reshape(16,1).shape)
print("New shape : ",  array_arange.reshape(1,16).shape)
# What is the data type of the object in the array?
print("Data Type : ", array_arange.dtype)

Shape :  (16,)
Size :  16
Type :  int64
Reshaped :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
New shape :  (4, 4)
New shape :  (16, 1)
New shape :  (1, 16)
Data Type :  int64


In [11]:
import numpy as np
array_2d= np.arange(24) # creating 1D array using arange() 
array_2d.shape = (6,4) # converting into 2D
print(array_2d) # How the 2D array look like!

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
# array_2d[:2,:2].shape gives (2,2), 
# 4 elements for top left corner
# array_2d[0:2,0:2] is same as array_2d[:2,:2]
print(array_2d[:2,:2])

# getting inner slice
print(array_2d[2:4,2:4])

[[0 1]
 [4 5]]
[[10 11]
 [14 15]]


In [13]:
#Broadcasting
# Let's create an array using arange()
array_1d = np.arange(0,10)
print("Original Array : ", array_1d)
array_1d[0:5] = 500
print("After Broadcasting : ", array_1d)

Original Array :  [0 1 2 3 4 5 6 7 8 9]
After Broadcasting :  [500 500 500 500 500   5   6   7   8   9]


In [14]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4))

print("2D Array")
print(array_2d)

# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
print("\n After Broadcasting")
print(array_2d)

2D Array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 After Broadcasting
[[300. 300. 300. 300.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]


In [15]:
# Lets create a simple 1-D array and broadcast it to array_2d
print( array_2d + np.arange(0,4) )

[[300. 301. 302. 303.]
 [  1.   2.   3.   4.]
 [  1.   2.   3.   4.]
 [  1.   2.   3.   4.]]


In [16]:
array_1 = np.arange(1,4)
array_2 = np.arange(1,4)[:, np.newaxis]
# The official way of printing is used, format() and len() are used for revisions

print(array_1)
print("Shape of the array is: {}, this is {}-D array \n"
      .format(array_1.shape,len(array_1.shape)))
# (3,) indicates that this is a one-dimensional array (vector)

print(array_2)
print("Shape of the array is: {}, this is {}-D array"
      .format(array_2.shape,len(array_2.shape)))
# (3,) indicates that this is a one-dimensional array (vector)

[1 2 3]
Shape of the array is: (3,), this is 1-D array 

[[1]
 [2]
 [3]]
Shape of the array is: (3, 1), this is 2-D array


In [17]:
#Boolean Masking
# Creating a simple array using arange()
array_1d = np.arange(1,11)
print("Original Array : ", array_1d )

# lets create a bool_array for some condition, say array_1d > 3
bool_array = array_1d > 3
print("Is Greater than 3 Array : ", bool_array )

# A number is even, if number % 2 is 0
mod_2_mask_1d = 0 == array_1d % 2
print("IsEven Array : ", mod_2_mask_1d )

Original Array :  [ 1  2  3  4  5  6  7  8  9 10]
Is Greater than 3 Array :  [False False False  True  True  True  True  True  True  True]
IsEven Array :  [False  True False  True False  True False  True False  True]


In [20]:
def getArray():
   # Your Code here
   ary = np.arange(0,25)
   ary = ary.reshape(5,5)
   ary = ary + 100


   return ary

getArray()

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124]])