In [1]:
#Pandas
import pandas as pd
import numpy as np

In [2]:
my_labels = ['X','Y','Z']
my_data = [100,200,300]

# Converting my_data (Python list) to pandas Series
print(pd.Series(data = my_data))

0    100
1    200
2    300
dtype: int64


In [3]:
print(pd.Series(data = my_data, index = my_labels))
#pd.Series(my_data, my_labels) 
# Same as above!, data and index are in order￿

X    100
Y    200
Z    300
dtype: int64


In [4]:
# Let's create NumPy array from my_data and then Series from that array 
my_array = np.array(my_data) # creating numpy's array from list 
series = pd.Series(data = my_array, index = my_labels) # creating Series from numpy's array
print(series)

X    100
Y    200
Z    300
dtype: int64


In [5]:
# Let's pass my_labels (which is a list of strings) as data now! 
print(pd.Series(data = my_labels)) # passing list for strings as data

# We can pass a list of built-in functions!
print(pd.Series([min, max, sum, print]))

0    X
1    Y
2    Z
dtype: object
0      <built-in function min>
1      <built-in function max>
2      <built-in function sum>
3    <built-in function print>
dtype: object


In [6]:
# Creating three dictionaries dict_1, dict_2, dict_3
dict_1 = {'Toronto': 500, 'Calgary': 200, 'Vancouver': 300, 'Montreal': 700}
dict_2 = {'Calgary': 200, 'Vancouver': 300, 'Montreal': 700}
dict_3 = {'Calgary': 200, 'Vancouver': 300, 'Montreal': 700, 'Jasper':1000}

# Creating Pandas Series from the dictionaries
ser1 = pd.Series(dict_1)
ser2 = pd.Series(dict_2)
ser3 = pd.Series(dict_3)

In [7]:
print("Series 1 : \n",ser1)
print("\nSeries 2 : \n",ser2)
print("\nSeries 3 : \n",ser3)

Series 1 : 
 Toronto      500
Calgary      200
Vancouver    300
Montreal     700
dtype: int64

Series 2 : 
 Calgary      200
Vancouver    300
Montreal     700
dtype: int64

Series 3 : 
 Calgary       200
Vancouver     300
Montreal      700
Jasper       1000
dtype: int64


In [8]:
ser4 = ser1 + ser2 
# adding Series and assigning/passing results to a new variable ser4
print(ser4)
print()
# What if we add ser4 and ser3, another NaN for Jasper!
ser5 = ser4 + ser3
print(ser5)

Calgary       400.0
Montreal     1400.0
Toronto         NaN
Vancouver     600.0
dtype: float64

Calgary       600.0
Jasper          NaN
Montreal     2100.0
Toronto         NaN
Vancouver     900.0
dtype: float64


DATAFRAME

In [9]:
index = 'r1 r2 r3 r4 r5 r6 r7 r8 r9 r10'.split()
columns = 'c1 c2 c3 c4 c5 c6 c7 c8 c9 c10'.split()
# just to see what the index looks like, a list from r1 to r10!
print(index)

# and what columns look like, a list from c1 to c10!
print(columns)

array_2d = np.arange(0,100).reshape(10,10) # creating a 2D array "array_2d"
print(array_2d)

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']
['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
df = pd.DataFrame(data = array_2d, index = index, columns = columns)
print(df)

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99


In [11]:
# Grabbing a single column
print("Column C1 : \n", df['c1'])#It's a pada series

Column C1 : 
 r1      0
r2     10
r3     20
r4     30
r5     40
r6     50
r7     60
r8     70
r9     80
r10    90
Name: c1, dtype: int64


In [12]:
df['new'] = df['c1'] + df['c2'] 
# adding a column "new" which is sum of "c1" and "c2"
print(df)

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new
r1    0   1   2   3   4   5   6   7   8    9    1
r2   10  11  12  13  14  15  16  17  18   19   21
r3   20  21  22  23  24  25  26  27  28   29   41
r4   30  31  32  33  34  35  36  37  38   39   61
r5   40  41  42  43  44  45  46  47  48   49   81
r6   50  51  52  53  54  55  56  57  58   59  101
r7   60  61  62  63  64  65  66  67  68   69  121
r8   70  71  72  73  74  75  76  77  78   79  141
r9   80  81  82  83  84  85  86  87  88   89  161
r10  90  91  92  93  94  95  96  97  98   99  181


In [13]:
df.drop(['c1'], axis = 1, inplace = True) 
# If we don't pass inplace = True, then change will not be permanent
print(df)

     c2  c3  c4  c5  c6  c7  c8  c9  c10  new
r1    1   2   3   4   5   6   7   8    9    1
r2   11  12  13  14  15  16  17  18   19   21
r3   21  22  23  24  25  26  27  28   29   41
r4   31  32  33  34  35  36  37  38   39   61
r5   41  42  43  44  45  46  47  48   49   81
r6   51  52  53  54  55  56  57  58   59  101
r7   61  62  63  64  65  66  67  68   69  121
r8   71  72  73  74  75  76  77  78   79  141
r9   81  82  83  84  85  86  87  88   89  161
r10  91  92  93  94  95  96  97  98   99  181


In [14]:
# using loc, this will return rows r2 and r3,
# notice the list [r2, r3] in square ,!brackets
print(df.loc[['r2', 'r3']])

    c2  c3  c4  c5  c6  c7  c8  c9  c10  new
r2  11  12  13  14  15  16  17  18   19   21
r3  21  22  23  24  25  26  27  28   29   41


In [15]:
print(df)
print("Element at r1,c2 : ", df.loc['r1','c2'])
print("Element at r2,c10 : ", df.loc['r2', 'c10'])

# for a subset, pass the list
print("Subset \n",df.loc[['r1','r2'],['c4','c2']])

# another example - random columns and rows in the list
print("Random Columns and Rows \n", df.loc[['r2','r5'],['c3','c4']])

     c2  c3  c4  c5  c6  c7  c8  c9  c10  new
r1    1   2   3   4   5   6   7   8    9    1
r2   11  12  13  14  15  16  17  18   19   21
r3   21  22  23  24  25  26  27  28   29   41
r4   31  32  33  34  35  36  37  38   39   61
r5   41  42  43  44  45  46  47  48   49   81
r6   51  52  53  54  55  56  57  58   59  101
r7   61  62  63  64  65  66  67  68   69  121
r8   71  72  73  74  75  76  77  78   79  141
r9   81  82  83  84  85  86  87  88   89  161
r10  91  92  93  94  95  96  97  98   99  181
Element at r1,c2 :  1
Element at r2,c10 :  19
Subset 
     c4  c2
r1   3   1
r2  13  11
Random Columns and Rows 
     c3  c4
r2  12  13
r5  42  43


Herarchial Indexing 

In [16]:
# Importing numpy and Pandas first
import numpy as np
import pandas as pd

# Set a random seed for reproducibility
np.random.seed(42)  # You can use any integer as the seed value

# Create a Series with a list of lists (or arrays) as the index: 
index = [['a','a','a','b','b','b','c','c','d','d'], # level 1 index 
         [1,2,3,1,2,3,1,2,1,2]] # level 2 index

# Let's create a Series "ser" with multi-level index (2 in this example)
ser = pd.Series(np.random.randn(10), index=index)
print(ser)

a  1    0.496714
   2   -0.138264
   3    0.647689
b  1    1.523030
   2   -0.234153
   3   -0.234137
c  1    1.579213
   2    0.767435
d  1   -0.469474
   2    0.542560
dtype: float64


In [17]:
ser.index.names = ['L_1', 'L_2']
print("Dataframe \n", ser)

Dataframe 
 L_1  L_2
a    1      0.496714
     2     -0.138264
     3      0.647689
b    1      1.523030
     2     -0.234153
     3     -0.234137
c    1      1.579213
     2      0.767435
d    1     -0.469474
     2      0.542560
dtype: float64


In [18]:
# Returns a cross-section (row(s) or column(s)) from the Series/DataFrame.
print(ser.xs('a'))

print(ser.xs(1, level='L_2'))

L_2
1    0.496714
2   -0.138264
3    0.647689
dtype: float64
L_1
a    0.496714
b    1.523030
c    1.579213
d   -0.469474
dtype: float64


Handling missing data

In [19]:
# Creating a data dictionary
data_dict = {'A':[1,2,np.nan,4,np.nan],
            'B':[np.nan,np.nan,np.nan,np.nan,np.nan],
            'C':[11,12,13,14,15],
            'D':[16,np.nan,18,19,20]}
# Creating DataFrame form data_dict
df = pd.DataFrame(data_dict) # DataFrame from a dic.

print(df)

     A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13  18.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0


In [20]:
# isnull() returns True if the data is missing
print(df.isnull())
print()
# notnull() returns True for non-NaN values
print(df.notnull())

       A     B      C      D
0  False  True  False  False
1  False  True  False   True
2   True  True  False  False
3  False  True  False  False
4   True  True  False  False

       A      B     C      D
0   True  False  True   True
1   True  False  True  False
2  False  False  True   True
3   True  False  True   True
4  False  False  True   True


In [21]:
# Sum on Column "A", (NaN as 0)
print(df['A'])
print("Sum : ", df['A'].sum())
# grabbing column 'A' and calling sum() ==> 1.0+2.0+NaN(0)+4.0+NaN(0)

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
Name: A, dtype: float64
Sum :  7.0


Combining and Merging Datasets

In [22]:
import numpy as np
import pandas as pd
df1 = pd.DataFrame({'key': ['a', 'b', 'c', 'd', 'e'],'A1': range(5), 'B1':range(5,10)})
df2 = pd.DataFrame({'key': ['a', 'b', 'c'], 'A2': range(3), 'B2':range(3,6)})
print("Dataframe 1\n", df1)
print("Dataframe 2\n", df2)

Dataframe 1
   key  A1  B1
0   a   0   5
1   b   1   6
2   c   2   7
3   d   3   8
4   e   4   9
Dataframe 2
   key  A2  B2
0   a   0   3
1   b   1   4
2   c   2   5


The how method tells merge() what type of joining operation needs to be done. The joining operation could be inner, outer, left, or right. The default value of how is inner.
The on method specifies what field name to join on. This could be a label or a list.

In [23]:
print("\nmerged (how = 'inner'): \n",pd.merge(df1, df2, how = 'inner', on='key'))



merged (how = 'inner'): 
   key  A1  B1  A2  B2
0   a   0   5   0   3
1   b   1   6   1   4
2   c   2   7   2   5


In [24]:
print("\nmerged (how = 'outer'): \n",pd.merge(df1, df2, how = 'outer', on='key'))


merged (how = 'outer'): 
   key  A1  B1   A2   B2
0   a   0   5  0.0  3.0
1   b   1   6  1.0  4.0
2   c   2   7  2.0  5.0
3   d   3   8  NaN  NaN
4   e   4   9  NaN  NaN


In [25]:
# creating two DataFrames, left and right
left = pd.DataFrame({'key1': ['a', 'a', 'b', 'c'],
                     'key2': ['a', 'b', 'a', 'b'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['a', 'b', 'b', 'c'],
                      'key2': ['a', 'b', 'a', 'a'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})
print("left is :\n", left)
print("\nright is :\n",right)
print("\nmerged (inner) on key1 and key2 is :\n",pd.merge(left, right, how = 'inner', on=['key1', 'key2']))

left is :
   key1 key2   A   B
0    a    a  A0  B0
1    a    b  A1  B1
2    b    a  A2  B2
3    c    b  A3  B3

right is :
   key1 key2   C   D
0    a    a  C0  D0
1    b    b  C1  D1
2    b    a  C2  D2
3    c    a  C3  D3

merged (inner) on key1 and key2 is :
   key1 key2   A   B   C   D
0    a    a  A0  B0  C0  D0
1    b    a  A2  B2  C2  D2


In [26]:
# creating two DataFrames, left and right
left = pd.DataFrame({'key1': ['a', 'a', 'b', 'c'],
                     'key2': ['a', 'b', 'a', 'b'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['a', 'b', 'b', 'c'],
                      'key2': ['a', 'b', 'a', 'a'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})
print("left is :\n", left)
print("\nright is :\n",right)
print("\nmerged (inner) on key1 and key2 is :\n",pd.merge(left, right, how = 'inner', on=['key1', 'key2']))

left is :
   key1 key2   A   B
0    a    a  A0  B0
1    a    b  A1  B1
2    b    a  A2  B2
3    c    b  A3  B3

right is :
   key1 key2   C   D
0    a    a  C0  D0
1    b    b  C1  D1
2    b    a  C2  D2
3    c    a  C3  D3

merged (inner) on key1 and key2 is :
   key1 key2   A   B   C   D
0    a    a  A0  B0  C0  D0
1    b    a  A2  B2  C2  D2


In [27]:
print("\nmerged (outer) on key1 and key2 is :\n", pd.merge(left, right, how='outer', on=['key1', 'key2']))
# notice NaN for the missing data!


merged (outer) on key1 and key2 is :
   key1 key2    A    B    C    D
0    a    a   A0   B0   C0   D0
1    a    b   A1   B1  NaN  NaN
2    b    a   A2   B2   C2   D2
3    c    b   A3   B3  NaN  NaN
4    b    b  NaN  NaN   C1   D1
5    c    a  NaN  NaN   C3   D3


Concatenation is an operation that glues DataFrames together. It’s interchangeably referred to as binding or stacking as well.

In [28]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4,5,6,7])
# the default axis is 0 'index' (rows) to concatenate along.
print("Default axis \n",pd.concat([df1,df2]))

# axis = 1 for columns
print("Axis = 1 \n", pd.concat([df1,df2],axis=1))

Default axis 
     A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
Axis = 1 
      A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7


GroupBy methods

In [1]:
import pandas as pd
# Create a DataFrame
data = {'Store':['Walmart','Walmart','Costco','Costco','Target','Target'],
       'Customer':['Tim','Jermy','Mark','Denice','Ray','Sam'],
       'Sales':[150,200,550,90,430,120]}

# Creating DataFrame
df = pd.DataFrame(data)
print(df)

     Store Customer  Sales
0  Walmart      Tim    150
1  Walmart    Jermy    200
2   Costco     Mark    550
3   Costco   Denice     90
4   Target      Ray    430
5   Target      Sam    120


In [2]:
# Let's create new grouped DataFrame "by_store" after grouping on "store" column
by_store = df.groupby("Store")
print(by_store)

In [3]:
print(by_store.mean())  

         Sales
Store         
Costco   320.0
Target   275.0
Walmart  175.0


/tmp/ipykernel_14652/2287033011.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(by_store.mean())


In [4]:
# In one line of code using sum ad loc methods
print(df.groupby('Store').sum().loc["Target"])
print("\nMinimum value of sale \n", by_store.min()) # minimum value of sale 
print("\nMaximum value of sale \n", by_store.max()) # maximum value of sale 
print("\nStandard deviation of sale \n", by_store.std()) # standard deviation of sale
# Let's count the number of instances in each column, this operation works with strings as well
# we have 2 customers for each store and 2 sales for each store
print("\nCount : ", by_store.count())

Sales    550
Name: Target, dtype: int64

Minimum value of sale 
         Customer  Sales
Store                  
Costco    Denice     90
Target       Ray    120
Walmart    Jermy    150

Maximum value of sale 
         Customer  Sales
Store                  
Costco      Mark    550
Target       Sam    430
Walmart      Tim    200

Standard deviation of sale 
               Sales
Store              
Costco   325.269119
Target   219.203102
Walmart   35.355339

Count :           Customer  Sales
Store                   
Costco          2      2
Target          2      2
Walmart         2      2


/tmp/ipykernel_14652/1686056223.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print(df.groupby('Store').sum().loc["Target"])
/tmp/ipykernel_14652/1686056223.py:5: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  print("\nStandard deviation of sale \n", by_store.std()) # standard deviation of sale


In [5]:
# summary statistics using describe on grouped DataFrame 
print(by_store.describe())
print()
# transpose after describe (two operations in one go!)
print(by_store.describe().transpose() )
print()
# summary statistics for Costco 
print(by_store.describe().transpose()['Costco'])

        Sales                                                      
        count   mean         std    min    25%    50%    75%    max
Store                                                              
Costco    2.0  320.0  325.269119   90.0  205.0  320.0  435.0  550.0
Target    2.0  275.0  219.203102  120.0  197.5  275.0  352.5  430.0
Walmart   2.0  175.0   35.355339  150.0  162.5  175.0  187.5  200.0

Store            Costco      Target     Walmart
Sales count    2.000000    2.000000    2.000000
      mean   320.000000  275.000000  175.000000
      std    325.269119  219.203102   35.355339
      min     90.000000  120.000000  150.000000
      25%    205.000000  197.500000  162.500000
      50%    320.000000  275.000000  175.000000
      75%    435.000000  352.500000  187.500000
      max    550.000000  430.000000  200.000000

Sales  count      2.000000
       mean     320.000000
       std      325.269119
       min       90.000000
       25%      205.000000
       50%      320.000

In [30]:
print(df)
customer_list = list(df[df['Sales'] > 100]['Customer'])
print(customer_list)




     Store Customer  Sales
0  Walmart      Tim    150
1  Walmart    Jermy    200
2   Costco     Mark    550
3   Costco   Denice     90
4   Target      Ray    430
5   Target      Sam    120
['Tim', 'Jermy', 'Mark', 'Ray', 'Sam']
